CREATE TABLE IF NOT EXISTS phone (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  user_id BIGINT(20) NOT NULL,
  number VARCHAR(18),
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES `user`(id)
) CHARACTER SET utf8 COLLATE utf8_general_ci;
