CREATE TABLE IF NOT EXISTS user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255),
  age INTEGER(3),
  address_id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (address_id) REFERENCES address(id)
) CHARACTER SET utf8 COLLATE utf8_general_ci;
